---
:api_key: 70a0d2e8d51bd9fc0a00061388564331
:password: 76d1681512fe074845b2cdc248693ecd
:store: xlr8-tx.myshopify.com
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
:theme_id: 8293908518
